plugin:
    has_options: false

    resource_actions:
      - name: hevinci_favourite

    widgets:
      - name: hevinci_favourite_widget
        is_configurable: false
        is_displayable_in_workspace: false